config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  resources :books, only: [:new, :create, :index, :edit, :update, :show, :destroy]
    resources :users, only: [:show, :index, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      render :index
    end
  end

  def show
    @book_new = Book.new
    @user = current_user
    @book = Book.find(params[:id])
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @users = User.all
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @books = Book.all
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

# params[:id]

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
  <div class="row">
    <%= link_to edit_user_path(user.id),class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
   </div>
  <!--<div class="col-md-3">-->
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: 'btn btn-success'%>
      </div>
    <% end %>
  <!--</div>-->

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: "form-control book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: "form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>

        <p><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %></p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', book: @book_new, user: @book.user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      	<table class="table">
      	  <tbody>
      		  <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                  <%= image_tag @book.user.get_profile_image(100,100) %><br><%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book),class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？",class: "btn btn-sm btn-danger" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
    </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div clss="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>


        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/75497fcafa.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home" ></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </p>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>